//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askmentor.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskmentorStagingEntities : DbContext
    {
        public AskmentorStagingEntities()
            : base("name=AskmentorStagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mentees_Tbl> Mentees_Tbl { get; set; }
        public virtual DbSet<temp_User_Tbl> temp_User_Tbl { get; set; }
        public virtual DbSet<User_Tbl> User_Tbl { get; set; }
    }
}
